export const TYPES = {
  Database: Symbol.for('Database'),
  HttpServer: Symbol.for('HttpServer'),
  AdCreateRepository: Symbol.for('AdCreateRepository'),
  AdFindRepository: Symbol.for('AdFindRepository'),
  AdListByGameRepository: Symbol.for('AdListByGameRepository'),
  DiscordFindByAdRepository: Symbol.for('DiscordFindByAdRepository'),
  GameListRepository: Symbol.for('GameListRepository'),
  GameCreateRepository: Symbol.for('GameCreateRepository'),
  AdCreateUsecase: Symbol.for('AdCreateUsecase'),
  AdFindUsecase: Symbol.for('AdFindUsecase'),
  AdListByGameUsecase: Symbol.for('AdListByGameUsecase'),
  DiscordFindByAdUsecase: Symbol.for('DiscordFindByAdUsecase'),
  GameListUsecase: Symbol.for('GameListUsecase'),
  GameCreateUsecase: Symbol.for('GameCreateUsecase'),
}
