name: Validate PR

on:
  pull_request:
    branches: [main, dev]

env:
  BRANCH: ${{ github.ref }}
  DATABASE_URL: ${{ secrets.development.DATABASE_URL }}
  PORT: ${{ secrets.PORT }}
  ENV_NAME: ${{ secrets.ENV_NAME }}

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Clone main repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build main repo
        run: tsc

      - uses: actions/checkout@v3
      - name: "Set up environment"
        run: docker compose -f docker-compose-test.yml up -d --wait

      - name: Wait docker run
        run: sleep 30

      - name: "Test server"
        run: docker exec app_database_test yarn test
